name: maddymail
services:
  maddy:
    container_name: maddy
    environment:
      - MADDY_HOSTNAME=mx.livelearnpro.com
      - MADDY_DOMAIN=livelearnpro.com
    volumes:
      - maddydata:/data
      - ./maddy/tls:/data/tls
      - ./generate_cert.sh:/usr/local/bin/generate_cert.sh  # Mount the script
    ports:
      - 25:25
      - 143:143
      - 465:465
      - 587:587
      - 993:993
    image: foxcpp/maddy:0.7
    restart: unless-stopped
    entrypoint: ["/usr/local/bin/generate_cert.sh"] # Execute the script on startup
volumes:
  maddydata:
    external: true
    name: maddydata
